# Generated by Django 2.2 on 2020-01-07 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='donatorApproved',
            field=models.ManyToManyField(blank=True, related_name='donator_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
