# Generated by Django 2.2 on 2020-01-07 22:35

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('donation', '0005_userprofile_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
