# Generated by Django 2.2 on 2020-01-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0007_auto_20200107_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='proof_video',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name=''),
        ),
    ]
