# Generated by Django 2.2 on 2020-01-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0008_auto_20200107_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='price_reached',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
