# Generated by Django 2.2 on 2020-01-08 17:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0009_auto_20200107_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='published',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
