# Generated by Django 2.2 on 2020-01-08 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0010_challenges_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='status',
            field=models.CharField(default='in_progress', max_length=20),
        ),
    ]
