# Generated by Django 2.2 on 2020-01-08 18:46

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0017_challenges_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenges',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
