# Generated by Django 2.2 on 2020-01-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0018_auto_20200108_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(related_name='follow', to='donation.UserProfile'),
        ),
    ]
