# Generated by Django 2.2 on 2020-01-09 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0019_userprofile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_followers',
            field=models.ManyToManyField(related_name='followers', to='donation.UserProfile'),
        ),
    ]
