# Generated by Django 2.2 on 2020-01-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0020_userprofile_user_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='follow', to='donation.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_followers',
            field=models.ManyToManyField(blank=True, related_name='followers', to='donation.UserProfile'),
        ),
    ]
