# Generated by Django 2.2 on 2020-01-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0022_auto_20200113_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='donated',
            field=models.ManyToManyField(blank=True, related_name='donated', to='donation.Challenges'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='down_vote',
            field=models.ManyToManyField(blank=True, related_name='down_vote', to='donation.Challenges'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='up_vote',
            field=models.ManyToManyField(blank=True, related_name='up_vote', to='donation.Challenges'),
        ),
    ]
