# Generated by Django 2.2 on 2020-01-17 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donation', '0023_auto_20200115_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonatedAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True)),
                ('challenge', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='amount_challenge', to='donation.Challenges')),
                ('user', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='amount_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
