# Generated by Django 2.2 on 2020-01-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0024_donatedamount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donatedamount',
            options={'verbose_name_plural': 'Donated Amount Transaction'},
        ),
    ]
