# Generated by Django 2.2 on 2020-01-17 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0025_auto_20200117_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donatedamount',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='donatedamount',
            name='challenge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='amount_challenge', to='donation.Challenges'),
        ),
        migrations.AlterField(
            model_name='donatedamount',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='amount_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
