# Generated by Django 2.2 on 2020-01-18 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0026_auto_20200117_1624'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challenges',
            options={'ordering': ['published'], 'verbose_name_plural': 'Challenges'},
        ),
    ]
