# Generated by Django 2.2 on 2020-01-20 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0028_auto_20200120_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='challengescomments',
            old_name='about',
            new_name='comment',
        ),
    ]
