# Generated by Django 2.2 on 2020-01-22 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0029_auto_20200120_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='challengescomments',
            options={'ordering': ['published'], 'verbose_name_plural': 'Challenges Comments'},
        ),
    ]
