# Generated by Django 2.2 on 2020-01-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0032_delete_usermanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challengescomments',
            name='user',
        ),
        migrations.AddField(
            model_name='challengescomments',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='donation.UserProfile'),
        ),
    ]
