# Generated by Django 2.2 on 2020-01-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0034_auto_20200122_1116'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChallengesComments',
        ),
    ]
